modLoader="javafml"
loaderVersion="[28,)"
updateJSONURL="https://raw.githubusercontent.com/MinecraftModDevelopmentMods/red-pandas/master/update.json"
issueTrackerURL="https://github.com/MinecraftModDevelopmentMods/red-pandas/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/red-pandas"
logoFile=""
credits="ProxyNeko"
authors="ProxyNeko"

[[mods]]
modId="redpandas"
version="${file.jarVersion}"
displayName="Red Pandas"
description='''
A small mod with just Red Pandas coz why not they are so cute!
'''

[[dependencies.redpanda]]
   modId="forge"
   mandatory=true
   versionRange="[28,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.redpanda]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.14.4]"
   ordering="NONE"
   side="BOTH"