name: Upload to Curseforge

on:
  push:
    paths:
      - 'gradle.properties'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Build
        run: chmod 777 gradlew
      - name: Build with Gradle
        id: build
        env:
          USE_ALPHAS: false
        run: ./gradlew setupGithubActions build
      - name: Create a Release
        id: create_release
        uses: meeDamian/github-release@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: redpandas-${{ steps.build.outputs.version }}
          draft: false
          prerelease: false
          files: build/libs/redpandas-${{ steps.build.outputs.version }}.jar
          gzip: false
      - name: Release on CurseForge
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CF_API_TOKEN }}
          project_id: 336675
          game_endpoint: minecraft
          file_path: build/libs/redpandas-${{ steps.build.outputs.version }}.jar
          changelog: Initial beta release
          display_name: RedPandas ${{ steps.build.outputs.version }}
          game_versions: minecraft-1-15:1.15.2,Java 8,Forge
          release_type: beta